// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8e_xu4o_23hImcWPpNoaTam4pag5-XPk',
    appId: '1:328866137881:web:081cfd7784b4bae3626788',
    messagingSenderId: '328866137881',
    projectId: 'fsyapp-b0455',
    authDomain: 'fsyapp-b0455.firebaseapp.com',
    storageBucket: 'fsyapp-b0455.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDssjq_hgmxHjQg92CYEV4KHnD86UQGiFw',
    appId: '1:328866137881:android:ef5df7edbd1e5009626788',
    messagingSenderId: '328866137881',
    projectId: 'fsyapp-b0455',
    storageBucket: 'fsyapp-b0455.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3EP3vvMwSmG4jqZrV9u7GxI9lE4ObiWk',
    appId: '1:328866137881:ios:bd9e3b6f458725da626788',
    messagingSenderId: '328866137881',
    projectId: 'fsyapp-b0455',
    storageBucket: 'fsyapp-b0455.firebasestorage.app',
    iosBundleId: 'com.example.appFsy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3EP3vvMwSmG4jqZrV9u7GxI9lE4ObiWk',
    appId: '1:328866137881:ios:bd9e3b6f458725da626788',
    messagingSenderId: '328866137881',
    projectId: 'fsyapp-b0455',
    storageBucket: 'fsyapp-b0455.firebasestorage.app',
    iosBundleId: 'com.example.appFsy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8e_xu4o_23hImcWPpNoaTam4pag5-XPk',
    appId: '1:328866137881:web:3192b9acfc9b7a98626788',
    messagingSenderId: '328866137881',
    projectId: 'fsyapp-b0455',
    authDomain: 'fsyapp-b0455.firebaseapp.com',
    storageBucket: 'fsyapp-b0455.firebasestorage.app',
  );
}
